# version: '3'
# services:
#   web:
#     build:
#     ports:
#       - "3010:3010"
#     db:
#       image: "postgres"
#       environment:
#         POSTGRES_ROOT_PASSWORD: 123456
#       volumes:
#         - db-data:/foo

#   volumes:

version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: productoverview
    volumes:
      - /Users/davidhan/data/pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
      postgres-data:
        driver: local